name 'do_artifactory'
issues_url 'https://github.com/JackChance/do_artifactory/issues'
source_url 'https://github.com/JackChance/do_artifactory'
license 'MIT'
maintainer 'Cameron Straka'
maintainer_email 'strakacameron@hotmail.com'
version '0.1.0'
