name 'artifactory_do'
chef_version '>=12.6.0'
issues_url 'https://github.com/JackChance/artifactory_do/issues'
source_url 'https://github.com/JackChance/artifactory_do'
license 'MIT'
maintainer 'Cameron Straka'
maintainer_email 'strakacameron@hotmail.com'
version '0.1.0'
